x-build_template: &build
  build: .
  networks:
    - backend-network
    - payment-processor

services:
  api1: &api
    <<: *build
    command: [ "/bin/api", "api" ]
    hostname: api1
    depends_on:
      - cache
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

  api2:
    <<: *api
    hostname: api2

  consumer1:
    <<: *build
    command: [ "/bin/api", "consumer" ]
    hostname: consumer1
    depends_on:
      - cache
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "80MB"

  cache:
    <<: *build
    command: [ "/bin/api", "cache" ]
    hostname: cache
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"

  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:80"
    networks:
      - backend-network
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "70MB"

networks:
  backend-network:
    driver: bridge
  payment-processor:
    external: true
