services:
  api1: &api
    build: .
    command: [ "/bin/api", "api" ]
    hostname: api1
    environment:
      - APP_PORT=8080
      - DB_URL=postgres://user:password@db:5432/rinha?sslmode=disable
      - REDIS_URL=redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - INSTANCE_ID=API-1
      - WORKER_CONCURRENCY=8
    networks:
      - rinha-net
      - payment-processor-net
    depends_on:
      - cache
      #redis:
      #  condition: service_healthy
    #deploy:
    #  resources:
    #    limits:
    #      cpus: "0.45"
    #      memory: "60MB"

  api2:
    <<: *api
    hostname: api2
    environment:
      - SERVER_HOST=8080
      - DB_URL=postgres://user:password@db:5432/rinha?sslmode=disable
      - REDIS_URL=redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - INSTANCE_ID=API-2
      - WORKER_CONCURRENCY=8

  consumer1: &consumer1
    build: .
    command: [ "/bin/api", "consumer" ]
    hostname: consumer1
    networks:
      - rinha-net
      - payment-processor-net
    depends_on:
      - cache
      #redis:
      #  condition: service_healthy

  consumer2:
    <<: *consumer1
    hostname: consumer2

    #deploy:
    #  resources:
    #    limits:
    #      cpus: "0.45"
    #      memory: "60MB"

  cache:
    build: .
    command: [ "/bin/api", "cache" ]
    hostname: cache
    networks:
      - rinha-net

  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - rinha-net
    #deploy:
    #  resources:
    #    limits:
    #      cpus: "0.15"
    #      memory: "30MB"

  #rabbitmq:
  #  image: rabbitmq:latest
  #  container_name: rabbitmq
  #  restart: always
  #  healthcheck:
  #    test: rabbitmq-diagnostics -q ping
  #    interval: 10s
  #    timeout: 10s
 #     retries: 5
 #   networks:
 #     - rinha-net
  #  ports:
  #    - 5672:5672
  #    - 15672:15672
   # environment:
    #  RABBITMQ_DEFAULT_USER: rinha
    #  RABBITMQ_DEFAULT_PASS: rinha
    #configs:
    # - source: rabbitmq-plugins
    #    target: /etc/rabbitmq/enabled_plugins
    #volumes:
    #  - rabbitmq-lib:/var/lib/rabbitmq/
    #  - rabbitmq-log:/var/log/rabbitmq
    #deploy:
    #  resources:
    #    limits:
    #      cpus: "0.25"
    #      memory: "100MB"

  db:
    image: postgres:12-alpine
    container_name: rinha-db
    restart: always
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    #  - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    networks:
      - rinha-net
    #deploy:
    #  resources:
    #    limits:
    #      cpus: "0.25"
    #      memory: "100MB"

  redis:
    image: redis:7.2-alpine
    container_name: rinha-redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - rinha-net

networks:
  rinha-net:
    driver: bridge
  payment-processor-net:
    name: payment-processor
    external: true

configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]."

volumes:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local
  db:
    driver: local