services:
  api1: &api
    build: .
    command: [ "/bin/api", "api" ]
    hostname: api1
    networks:
      - rinha-net
      - payment-processor-net
    depends_on:
      - cache
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

  api2:
    <<: *api
    hostname: api2

  consumer1: &consumer1
    build: .
    command: [ "/bin/api", "consumer" ]
    hostname: consumer1
    networks:
      - rinha-net
      - payment-processor-net
    depends_on:
      - cache
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "80MB"

  cache:
    build: .
    command: [ "/bin/api", "cache" ]
    hostname: cache
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "100MB"

  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "70MB"

networks:
  rinha-net:
    driver: bridge
  payment-processor-net:
    name: payment-processor
    external: true
